- build.gradle
- PLAT-517 Prepared Gradle Publication Settings
- set encoding for javadoc to UTF-8
- fixed applying of publish-plug-in and added components
- enabled signing of artifacts on publish
- removed hard-coded URL and commented file
- added validation for ossrhUrl
- PLAT-517 Improved Reading and Checking of Release Properties
> PLAT-517 Improved Reading and Checking of Release Properties

- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/WorkflowTransitionValidator.java
- added check of non-null before validating requiredVote string﻿
> PLAT-488 Fix exception in WorklowEditor

- build.gradle
Test Plan:
- Comment everything in `/home/lx/.gradle/gradle.properties`
- Run Gradle tasks with various parameters:
```
$ ./gradlew clean publish
...expect failure, with a message about missing target
$ ./gradlew clean publish -Pversion=10.0.99-SNAPSHOT
...expect failure, with a message about missing target
$ ./gradlew clean publish -PossrhTarget=local
...expect failure, with a message about missing version
$ ./gradlew clean publish -Pversion=10.99.2 -PossrhTarget=local
...expect success, with appropriately-versioned artifacts generated to /home/<user>/.softicar/maven-local
$ ./gradlew clean assemble
...expect success.
$ ./gradlew publish --no-parallel -Pversion=10.99.2 -PossrhTarget=remote
...expect failure, with a message about undefined 'signing.keyId'. Define it, and try again. …
```
> PLAT-571 Enable local publishing of unsigned artifacts

- platform-core-module/src/main/java/com/softicar/platform/core/module/ajax/exception/view/InfoPopupCreator.java
After provoking an exception, open AjaxExceptionsPage (Core >> AJAX >> AJAX Exceptions) and check if you can click the button in column "Session" without getting NPE.
> PLAT-179 Fix NPE in AJAX Exceptions Page if no revision exists

- platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramStarter.java
Test plan:
To reproduce the error add to `BufferedEmailSendProgram` in line 21:
```
System.out.println(CurrentUser.get().getLoginName());
```
When you start `BufferedEmailSendProgram` you will see that the login name of the logged-user is printed on console.
After the patch "system.user" will be printed out instead.
> PLAT-565 Set systemUser as currentUser before executing programs

- platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-button-style.css
Eliminates another widespread (and unnecessary) use of `display: grid`.
Test Plan:
Ensure that buttons look exactly like before this PR.
> PLAT-612 Use flex layout for button labels

- build.gradle
- All `9.x` series Jetty versions up to `9.4.40` have known vulnerabilities.
- `9.4.44` does not. It is also the latest release in the `9.x` series. So we upgrade to that.
Test Plan:
- Ensure that this generates no output: `./gradlew allDependencies | grep FAIL`
- Ensure that all tests are green: `./gradlew clean check`
- Note that a Jetty server is used during Selenium test execution.
- Start a local test servlet (which also uses Jetty). Ensure that you can log in, and access and use pages as usual.
> PLAT-622 Upgrade jetty to 9.4.44

- build.gradle
- All `commons-compress` versions below `1.21` have known vulnerabilities.
- We need `commons-compress` as a dependency of `poi-ooxml`, so we now enforce `1.21`.
Test Plan:
- Ensure that this generates no output: `./gradlew allDependencies | grep FAIL`
- Ensure that `commons-compress:1.21` is used as a dependency of `poi-ooxml`: `./gradlew allDependencies | grep -B10 compress`
- Ensure that all tests are green: `./gradlew clean check`
> PLAT-621 Upgrade commons-compress to 1.21

- platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-action-bar-style.css
- platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-button-style.css
- platform-emf/src/main/resources/com/softicar/platform/emf/emf-form-style.css
- The height of a decorated button is no longer determined as the result of the min-height of the label element, and a vertical padding.
- Instead, it's now a fixed height on the button itself.
- This paved the way to use `display: inline` on `DomButtonLabel` which in turn fixes the previously-broken `text-overflow: ellipsis` for long button labels.
Test Plan:
see screenshots
> PLAT-638 DomButton: Use ellipsis for long button labels

- platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/AGProgramExecution.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/scheduled/ScheduledProgramEnqueuer.java
- platform-core-module/src/test/java/com/softicar/platform/core/module/program/execution/scheduled/ScheduledProgramEnqueuerTest.java
- When processing a program schedule, `ScheduledProgramEnqueuer` now properly ignores other running programs.
- This fixes `ScheduledProgramEnqueuer` erroneously skipping (i.e. not enqueuing) the due execution of a program, in case an arbitrary other program was running during the check.
Test Plan:
see added unit tests
> PLAT-639 Fix ScheduledProgramEnqueuer skipping executions

- platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/engine/level/high/AjaxSeleniumTestEngine.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/node/tester/AbstractDomNodeTester.java
Added context-click (i.e. "right-click") support to `AjaxSeleniumTestEngine`.
> PLAT-652 AjaxSeleniumTestEngine: Support context-clicks

- build.gradle
The enforced `byte-buddy` version had to be upgraded as well.
> PLAT-653 Upgrade mockito to 4.3.1

- build.gradle
- platform-core-module/src/main/java/com/softicar/platform/core/module/component/external/license/rule/ExternalComponentLicensePredefinedRules.java
Note: guava 27+ has an artificial dependency on `com.google.guava:listenablefuture`. We had to add a license matcher rule for that.
> PLAT-629 Upgrade guava to 31.0.1

- platform-emf/src/main/resources/com/softicar/platform/emf/emf-form-style.css
The underlying problem was not the CommonActions Div, but the `EmfFormPopupContainer` not using the whole width of the popup. The CommonActions were always aligned to the right, but if the parent isnt wide enough, it would look like its not.
> PLAT-646 Adjust Alignment of CommonActions

- platform-emf/src/main/java/com/softicar/platform/emf/EmfCssClasses.java
- platform-emf/src/main/java/com/softicar/platform/emf/table/row/EmfTableRowDisplay.java
- platform-emf/src/main/resources/com/softicar/platform/emf/emf-display-style.css
- Changed `EmfTableRowDisplay` to display a popup button for the referenced entity, instead of plain text.
- This way, the user can "follow an FK", and view the referenced entity in a popup.
- Note that this is totally generic. The gif below just provides random examples.
> PLAT-669 Spawn entity popups from table-row display elements

- platform-core-module/src/main/java/com/softicar/platform/core/module/email/buffer/BufferedEmailSendProgram.java
Summary:
* ﻿`BufferedEmailSendProgram` sends mails only via the (active) servers that
are connected to the unsent mails
Test Plan:
* To test changed SQL select you can temporarily add
```
com.softicar.platform.common.core.logging.LogLevel.VERBOSE.set();
```
to `BufferedEmailSendProgram`, inside method `sendForAllServers()` just before the changed select statement.
> PLAT-563 BufferedEmailSendProgram Must Not Try to Use All Servers

- platform-db-core/src/main/java/com/softicar/platform/db/core/connection/DbConnection.java
Contracy to the H2 driver, the MariaDB driver seems to not flag an RS column as auto-increment if, during an insert, a value was explicitly defined for that column.
Test Plan:
- Create a local snapshot release of the platform.
- Use that release in an EAS checkout.
- Create a war file from that EAS checkout.
- Deploy the war file on the Tomcat server of a SoftiCAR machine with persistent MariaDB.
- Open the login URL, and use your credentials to log in.
- Note that the login works (results in an error message w/o this PR).
> PLAT-685 DbConnection: Fix a wrong assumption about ResultSet metadata

- platform-core-module/src/main/java/com/softicar/platform/core/module/ajax/exception/cleanup/AjaxExceptionCleanupProgram.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/abort/ProgramAbortAction.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/enqueue/ProgramEnqueueAction.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/unqueue/ProgramUnqueueAction.java
Open the `Programs` page in a test servlet
Click `Enqueue` and observe the `queued at` field properly refreshing
Do the same with Abort and Unqueue and observe the same behavior
Unrelated: `AjaxExceptionCleanupProgram` now properly shows log output instead of console Ouput
> PLAT-688 Fix AGProgram Actions refreshing transient fields

- platform-core-module/src/main/java/com/softicar/platform/core/module/program/AGProgram.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/AGProgramTable.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramAbortRequestedField.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramCurrentExecutionField.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramField.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramQueuedAtField.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramQueuedByField.java
- PLAT-692 Add `ProgramField` to `AGProgram` to be able to sort table by name
- Put program column behind ID column
- Reduce visibility of *Field classes (unrelated to PLAT-692)
See Program Page, it shows ID column, too, now, and therefore looks like other pages.
The bug was fixed: You can sort by Program column, now.
Filtering by program is also possible.
> PLAT-692 Fix Chaotic Row Order of Table of Program Page

- platform-core-module/src/main/java/com/softicar/platform/core/module/access/module/instance/AGModuleInstanceTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/column/handler/EmfDataTableNonSortableColumnHandler.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/column/handler/EmfDataTableNonSortableNonFilterableColumnHandler.java
- Add `EmfDataTableNonSortableColumnHandler`
- `EmfDataTableNonSortableNonFilterableColumnHandler` extends `EmfDataTableNonSortableColumnHandler` now
- Use `EmfDataTableNonSortableColumnHandler` for column "Module Class"
No option to sort column "Module Class" anymore, but filter option is still available:
> PLAT-707 Module Instances Page: Column "Module Class" must not be sortable anymore

- platform-common-string/src/test/java/com/softicar/platform/common/string/formatting/MemoryFormattingTest.java
Insert...
`Locale.setDefault(Locale.GERMAN);`
.. at line 14 of class `MemoryFormattingTest`. => The tests will not fail.
> PLAT-713 Use Current Locale Specific Decimal Separator

- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/AbstractAjaxAutoCompleteStringTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/AjaxAutoCompleteChangeEventTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AbstractAjaxAutoCompleteEntityTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AjaxAutoCompleteEntityInputCreatedTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AjaxAutoCompleteEntityInputFocusedPopupClosedTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AjaxAutoCompleteEntityInputFocusedPopupOpenedTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AjaxAutoCompleteEntityInputFocusedPopupReclosedTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AjaxAutoCompleteEntityInputFocusedPopupUnopenedTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AjaxAutoCompleteEntityInputFocusedTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AjaxAutoCompleteEntityInputRefocusedTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/entity/AjaxAutoCompleteEntityInputUnfocusedTest.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteInput.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteInputSelection.java
- platform-dom/src/main/java/com/softicar/platform/dom/input/IDomValueInput.java
- platform-dom/src/main/java/com/softicar/platform/dom/input/auto/IDomAutoCompleteInput.java
- platform-dom/src/main/java/com/softicar/platform/dom/input/auto/IDomAutoCompleteInputSelection.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/enums/table/row/EmfEnumTableRowInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/foreign/entity/input/EmfEntityInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/management/prefilter/AbstractEmfPrefilterRow.java
- Let `IDomAutoCompleteInput` extend `IDomValueInput`, and adopt recent changes to the `IDomValueInput` API.
- Reworked `IDomAutoCompleteInputSelection`, and the return values in its implementation.
- Adopted expected behavior changes in unit tests.
- Fixed permissive mode.
> PLAT-744 Let IDomAutoCompleteInput extend IDomValueInput

- platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/table/configuration/DbTableConfigurationCodeValidator.java
Temporarily disabled `DbTableConfigurationCodeValidator`, until after Platform-17 was released.
> PLAT-744 Temporarily disable DbTableConfigurationCodeValidator

- platform-demo-module/src/main/java/com/softicar/platform/demo/module/moment/AGDemoMomentTable.java
- platform-demo-module/src/main/java/com/softicar/platform/demo/module/moment/DemoMomentDayInput.java
- platform-demo-module/src/main/java/com/softicar/platform/demo/module/moment/DemoMomentPointInTimeInput.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/bool/EmfBooleanInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/day/EmfDayInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/decimal/EmfDecimalAttribute.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/enums/EmfEnumInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/enums/table/row/EmfEnumTableRowInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/foreign/entity/input/EmfEntityInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/integer/EmfIntegerInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/longs/EmfLongInput.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/input/IEmfInput.java
- `setValueAndHandleChangeCallback` in `IEmfInput` manually executes the change-callback, if present
- previously, if setting a value of an input with just `setValue`, no change-callback was executed, which lead to some problems
- added a test implementation in `AGDemoMoment` where a button sets the value of the input with the new method
- added a dependee of the field that gets its value set programmatically that updates its value via `refreshInputConstraints`
> PLAT-733 IEmfInput: Add setValueAndHandleChangeCallback

- platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/DemoInvoiceForm.java
- platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/paid/DemoInvoicePaymentForm.java
- platform-emf/src/main/java/com/softicar/platform/emf/form/EmfFormMode.java
- platform-emf/src/main/java/com/softicar/platform/emf/form/delegator/AbstractEmfAdjacentNodeForm.java
- platform-emf/src/main/java/com/softicar/platform/emf/form/delegator/AbstractEmfFormDelegator.java
Added `AbstractEmfAdjacentNodeForm` to facilitate displaying an additional node next to an `EmfForm` (without having to write the same code over and over again).
Untelated: Minor renaming and Javadoc improvement.
> PLAT-762 Create AbstractEmfAdjacentNodeForm

- platform-core-module/src/main/java/com/softicar/platform/core/module/localization/AGLocalization.sqml
- platform-core-module/src/main/java/com/softicar/platform/core/module/localization/AGLocalizationGenerated.java
Test Plan: Try to create a new localization with empty digit group separator. Observe that it works.
> PLAT-761 Made `AGLocalization.digitGroupSeparator` Optional Again

- platform-ajax/src/test/java/com/softicar/platform/ajax/dialog/AjaxModalAlertPopupTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/dialog/AjaxModalConfirmPopupTest.java
- platform-ajax/src/test/java/com/softicar/platform/ajax/dialog/AjaxModalPromptPopupTest.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/user/password/UserPasswordGenerator.java
- platform-dom/src/main/java/com/softicar/platform/dom/DomCssPseudoClasses.java
- platform-dom/src/main/java/com/softicar/platform/dom/DomI18n.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/dialog/DomModalAlertPopup.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/dialog/DomModalConfirmPopup.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/dialog/DomModalPromptPopup.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/DomPopup.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomDefaultPopupCompositor.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomModalPopupBackdropStack.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomParentNodeFetcher.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomPopupFrameHighlighting.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomPopupHierarchyGraph.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/node/tester/AbstractDomNodeTester.java
- platform-dom/src/main/java/com/softicar/platform/dom/node/IDomNode.java
- platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-popup-style.css
- platform-dom/src/test/java/com/softicar/platform/dom/elements/dialog/DomModalAlertPopupTest.java
- platform-dom/src/test/java/com/softicar/platform/dom/elements/dialog/DomModalConfirmPopupTest.java
- platform-dom/src/test/java/com/softicar/platform/dom/elements/dialog/DomModalPromptPopupTest.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/EmfDataTableFilterButton.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/EmfDataTableFilterPopup.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/demo/WorkflowDemoObjectStartWorkflowAction.java
- Establish a hierarchy of `DomPopup` nodes, and let `DomDefaultPopupCompositor` handle it gracefully.
- If a popup was spawned from a node in another popup, a child-to-parent relation exists between those popups.
- When trying to close a popup that has at least one child popup, the compositor will ask for confirmation, and highlight the affected popups.
- If the user confirms, the popup and its transitive child popups are closed. If the user cancels, only the highlighting is removed.
- Due to this mechanism, orphaned popups are no longer a thing.
- `DomModalConfirmPopup` now allows for the specification of a cancel handler.
- Added new tests in `DomModalConfirmPopupTest`.
- Extracted various helper classes from `DomDefaultPopupCompositor`.
- Fixed PLAT-823 along the way.
- Semi-related …
> PLAT-824 Popup Compositor: Handle popup hierarchy

- platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-data-table-style.css
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/EmfDataTableDivBuilder.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/header/secondary/EmfDataTableExtraRowDefinition.java
- Removed hardstyled text-alignment
- Alignment is now default, which is center
- Added convenience method for NumericCells in footer, which has right-alignment
- Example:
> PLAT-857 Correctly Style Footer Rows in DomDataTable

- platform-dom/src/main/java/com/softicar/platform/dom/elements/DomElementsCssClasses.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/dialog/DomModalDialogPopup.java
- platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-modal-popup-style.css
`DOM_MODAL_DIALOG_POPUP_WRAPPED` was set exactly if `DOM_MODAL_DIALOG_POPUP` was set. Hence redundant.
> PLAT-872 DomModalDialogPopup: Remove an unnecessary CSS class

- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomDefaultPopupCompositor.java
- platform-dom/src/test/java/com/softicar/platform/dom/elements/popup/compositor/DomDefaultPopupCompositorTest.java
- Modal backdrops are no longer displayed full-page, by default. Instead, the closest maximization context (if any) is preferred as a parent.
- Popups spawned from modal popups are now also appended to the closest maximization context (instead of being appended to the body).
This has the following effects:
- Modal backdrops spawned from a page are displayed inside the `PageContentDiv`. They are no longer overlays above the entire viewport.
- Navigation and page header can be interacted with, while a modal popup spawned from a page is present.
- If a modal popup is spawned from outside the page (e.g. from the logout button), backdrop and popup will still be appended to the body.
- Fixed: Popups that were spawned from an EMF management table action popover are now in the same z-index …
> PLAT-875 Append modal popups and backdrops to the closest maximization context

- platform-core-module/src/main/java/com/softicar/platform/core/module/test/SofticarTestDatabase.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/web/service/test/WebServiceTestServer.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/web/service/test/WebServiceTestService.java
- platform-db-core/src/main/java/com/softicar/platform/db/core/database/IDbDatabase.java
- As requested, `WebServiceTestServer` now takes `IDbDatabase` instead of `SofticarTestDatabase`
- For this to work, the method `SofticarTestDatabase.applyFixture()` was generalized into `IDbDatabase.apply()`
- retained deprecated method `SofticarTestDatabase.applyFixture()` delegating to `IDbDatabase.apply()`
- Existing code is easy to adapt, just call `apply` instead of `applyFixture`:
> PLAT-937 Generalized applyFixture() Method from SofticarTestDatabase to IDbDatabase

- platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/preview/pdf/StoredFilePdfToZoomableImagesConverter.java
For a well-known test PDF, this change reduces the rendering time per page from ~1500 ms to ~320 ms, at the cost of an apparently marginal loss in quality.
> PLAT-961 Allow subsampling to boost PDF preview rendering

- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/manager/DomPopupManager.java
The static getter should be the only way to retrieve an instance.
> PLAT-1015 DomPopupManager: Change CTOR to private

- platform-ajax/src/main/resources/com/softicar/platform/ajax/ajax-style.css
We recently changed the parent element of the auto-complete popover to fix positioning when the page is scrolled. That change caused the regression fixed in this PR.
> PLAT-1007 Fix font color in auto-complete popover if input is in error state

- build.gradle
- platform-common-pdf/build.gradle
- platform-core-module/build.gradle
- platform-core-module/src/main/java/com/softicar/platform/core/module/component/external/license/rule/ExternalComponentLicensePredefinedRules.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/license/License.java
See:
- https://pdfbox.apache.org/2.0/dependencies.html#optional-components
- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox/2.0.26 (optional dependency on `jai-imageio-jpeg2000` is wrongfully displayed as "Test Dependency", most likely due to a defect in the `pom.xml` parser of mavencentral)
- https://github.com/jai-imageio/jai-imageio-jpeg2000
> PLAT-989 PDF previews: Enable rendering of jpeg2000-encoded embedded images

- platform-dom/src/main/resources/com/softicar/platform/dom/dom-style.css
Contrary to PLAT-1030s description, checkbox height in my tests were 26px while other rows were 27px high.
Since scaling up the checkbox looks absurd, I reduced the height of inputs to 14px instead of 15px so that all input rows are now 26px high
Chrome: 
Firefox:
> PLAT-1030 Adapted height of inputs

- platform-ajax/src/main/java/com/softicar/platform/ajax/document/AjaxDomDeferredInitializationControllerTest.java
- platform-ajax/src/main/java/com/softicar/platform/ajax/engine/AjaxDomEngine.java
- platform-common/src/main/java/com/softicar/platform/common/testing/Asserts.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/page/PageHeaderAndContentDiv.java
- platform-dom/src/main/java/com/softicar/platform/dom/document/AbstractDomDocument.java
- platform-dom/src/main/java/com/softicar/platform/dom/document/IDomDocument.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomParentNodeFinder.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/engine/AbstractDomTestExecutionEngineLazySetup.java
- platform-dom/src/main/java/com/softicar/platform/dom/engine/DomTestEngine.java
- platform-dom/src/main/java/com/softicar/platform/dom/event/DomEventHandlerNodeCaller.java
- platform-dom/src/main/java/com/softicar/platform/dom/node/IDomNode.java
- platform-dom/src/main/java/com/softicar/platform/dom/node/initialization/AbstractDomDeferredInitializationControllerTest.java
- platform-dom/src/main/java/com/softicar/platform/dom/node/initialization/DomDeferredInitializationController.java
- platform-dom/src/main/java/com/softicar/platform/dom/node/initialization/IDomDeferredInitializationController.java
- platform-dom/src/test/java/com/softicar/platform/dom/elements/popup/compositor/DomParentNodeFinderTest.java
- platform-dom/src/test/java/com/softicar/platform/dom/node/initialization/DomDeferredInitializationControllerTest.java
Allows for execution of an initialization callback as soon as a node obtains a transitive parent connection to the `DomBody`.
> PLAT-1048 Implement DomDeferredInitializationController

- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomDefaultPopupCompositor.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/compositor/DomPopupHierarchyGraph.java
- platform-dom/src/test/java/com/softicar/platform/dom/elements/popup/compositor/DomPopupHierarchyGraphTest.java
- Renamed `removeAllNonMatching` to `removeAllClosedLeaves` (stronger semantics: intended), and reworked it.
- The method no longer removes a closed parent popup from the graph if that popup still has at least one open child popup.
> PLAT-1044-1 DomPopupHierarchyGraph: Always retain closed parent popups

- build.gradle
- platform-core-module/build.gradle
- platform-core-module/src/main/java/com/softicar/platform/core/module/component/external/license/rule/ExternalComponentLicensePredefinedRules.java
- Added dependency on `imageio-jpeg`.
- Fixes "Numbers of source Raster bands and source color space components do not match" when trying to render certain JPEGs.
- See https://stackoverflow.com/questions/18351583/illegalargumentexception-numbers-of-source-raster-bands-and-source-color-space/18400559#18400559
> PLAT-1074 Fix previews for PDFs with certain embedded JPEGs

- platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/preview/pdf/StoredFilePdfToZoomableImagesConverter.java
- Both the comment and the referenced issue were devoid of helpful information.
- If "something" "sometimes" goes wrong "somehow", we should make the encountered Throwable observable, instead of swallowing it. Did that.
> PLAT-1081-3 StoredFilePdfToZoomableImagesConverter: Remove a legacy issue reference

- platform-ajax/src/main/java/com/softicar/platform/ajax/engine/AjaxDomEngine.java
- platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/TypeScriptGenerated.js
- platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/Constants.ts
- platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/event/DomEvent.ts
- platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/event/DomKeyboardEvents.ts
- platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/event/DomWheelEvents.ts
- platform-dom/src/main/java/com/softicar/platform/dom/engine/DomNullEngine.java
- platform-dom/src/main/java/com/softicar/platform/dom/engine/IDomEngine.java
- platform-dom/src/main/java/com/softicar/platform/dom/event/DomModifier.java
We currently cannot write automated tests for this. We could try https://www.selenium.dev/documentation/webdriver/actions_api/wheel/ but that would require a switch to Chrome based Selenium nodes. So, this PR was only tested manually.
There are 12 events in this GIF:
- 3x `WHEEL_DOWN` (default behavior allowed = scrolling)
- 3x `Shift + WHEEL_DOWN` (default behavior suppressed = NO scrolling)
- 3x `WHEEL_DOWN` (default behavior allowed = scrolling)
- 3x `Shift + WHEEL_DOWN` (default behavior suppressed = NO scrolling)
This is the wheel test element that can be seen in the GIF:
```
private class WheelTestDiv extends DomDiv implements IDomWheelEventHandler {
public WheelTestDiv() {
appendText("wheel me");
setStyle(CssStyle.BACKGROUND_COLOR, "yellow"); …
```
> PLAT-1136-2 Implement setPreventDefaultOnWheel

- platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/structure/comparison/column/DbColumnStructureEqualityComparer.java
- platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/structure/comparison/helper/DbTableStructureFeatureIdentifier.java
- platform-db-runtime/src/test/java/com/softicar/platform/db/runtime/structure/comparison/foreign/key/DbStructureCompatibleReferenceExklusiveConstraintTest.java
- platform-db-runtime/src/test/java/com/softicar/platform/db/runtime/structure/comparison/foreign/key/DbStructureCompatibleSampleExklusiveConstraintTest.java
- platform-db-runtime/src/test/java/com/softicar/platform/db/runtime/structure/comparison/foreign/key/DbStructureRestrictiveReferenceExclusiveConstraintTest.java
- platform-db-runtime/src/test/java/com/softicar/platform/db/runtime/structure/comparison/foreign/key/DbStructureRestrictiveSampleExclusiveConstraintTest.java
- platform-db-structure/src/main/java/com/softicar/platform/db/structure/foreign/key/IDbForeignKeyStructure.java
* PLAT-1152-3 No longer tolerate FK name deviations
* fix expected warning and error counts
> PLAT-1152-3 No longer tolerate FK name deviations (#493)

- platform-ajax/src/main/java/com/softicar/platform/ajax/upload/AjaxUploadService.java
- platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/TypeScriptGenerated.js
- platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/Upload.ts
- platform-core-module/src/main/java/com/softicar/platform/core/module/CoreCssClasses.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/CoreCssFiles.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/file/upload/FileDropArea.java
- platform-core-module/src/main/resources/com/softicar/platform/core/module/file-drop-area-style.css
- platform-dom/src/main/java/com/softicar/platform/dom/document/AbstractDomDocument.java
- platform-dom/src/main/java/com/softicar/platform/dom/document/DomDocumentEventScope.java
- platform-dom/src/main/java/com/softicar/platform/dom/document/IDomDocument.java
- platform-dom/src/main/java/com/softicar/platform/dom/event/DomEventHandlerNodeCaller.java
- Add `FileDropArea` from a payload project (blunt extraction; no refactoring).
- Create `DomDocumentEventScope`, and use it in `AjaxUploadService`.
- Set window geometry and fake event coordinates in `Upload.ts`.
- Assumed that the top-left corner of the form is sensible (as in: better than nothing) as event coordinates.
> PLAT-991-1 Fix context and coordinates of popups that are spawned from drag-and-drop file uploads

- platform-ajax/src/test/java/com/softicar/platform/ajax/waiting/div/AjaxWaitingDivTest.java
- Assert waiting-indicator state with `FluentWait`.
- Do not test the thing with itself (i.e. avoid `waitForServer`).
> PLAT-1185 AjaxWaitingDivTest: Fix non-determinisms

- platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramPage.java
Previously, `CorePermissions.ADMINISTRATION` was erroneously required.
A user which only has `CorePermissions.OPERATION` can now enqueue programs:
> PLAT-1191 ProgramPage now requires CorePermissions.OPERATION

- platform-ajax/src/main/java/com/softicar/platform/ajax/request/AjaxRequest.java
- platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/AjaxSeleniumTestEnvironment.java
- platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/engine/common/AbstractAjaxSeleniumTestEngine.java
- platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/engine/level/high/AjaxSeleniumTestExecutionEngine.java
- platform-common/src/main/java/com/softicar/platform/common/network/url/Url.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/ajax/page/EmfPageConnectionProfiler.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/page/PageUrlBuilder.java
- platform-core-module/src/test/java/com/softicar/platform/core/module/page/PageDivTest.java
- this is about the parameters `debug`, `profiler`, `stacktrace` and `verbose`
- without this change, only the initial page request will respect the mentioned debugging parameters which makes it impossible to debug/profile clicks on buttons, etc.
> PLAT-1200 Retain URL Debugging Parameters

- platform-core-module/src/main/java/com/softicar/platform/core/module/page/PageHeaderAndContentDiv.java
- this is a quick fix to prevent dangling refresh bus listeners to pile up, degrading performance
- we can consider to remove this quick fix later
> PLAT-1201 Explicit GC on Page Change

- platform-demo/src/test/java/com/softicar/platform/demo/invoice/module/invoice/stale/StaleDemoInvoiceRefreshTest.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/engine/AbstractDomTestExecutionEngineLazySetup.java
Once again discard refresh bus events that predate the creation of the node-under-test.
> PLAT-1196-2 Discard premature refresh bus events

- platform-core-module/src/main/java/com/softicar/platform/core/module/test/fixture/CoreModuleTestFixture.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/test/instance/registry/TestFixtureRegistry.java
- Eliminated constructor-with-side-effect pattern.
- This change is transparent to projects derived from the platform (this was tested manually).
> PLAT-1204 Let CoreModuleTestFixture implement IModuleTestFixture

- platform-core-module/src/main/java/com/softicar/platform/core/module/email/mailbox/imap/ImapMessage.java
Calling code in a payload project revealed that the implementation before this PR could indeed return _null_.
> PLAT-1209 ImapMessage: Fix getSubject to never return null

- build.gradle
- platform-core-module/build.gradle
- Use `com.sun.mail:jakarta.mail`
- ...instead of three single artifacts, `com.sun.mail:[mailapi|imap|smtp]`
- ...none of which provides `/META-INF/javamail.default.address.map`.
> PLAT-1212 Use combined jakarta.mail artifact to avoid spam in catalina.out

- platform-dom/src/main/java/com/softicar/platform/dom/elements/DomImage.java
Test Plan:
- Before applying this PR, change `AjaxDomEngineTest.testSetAlternateResourceOnErrorWithTiff` so that `System.gc()` gets called directly after `openTestNode`.
- Watch the test fail consistently.
- Apply this PR.
- Watch the test pass consistently.
> PLAT-1222 DomImage: Ensure that alternate resources are not garbage-collected

- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/matching/DomAutoCompleteMatchEntryComparator.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/matching/DomAutoCompleteMatchesBuilder.java
Added an internal cache to be used when normalization is enabled.
In a real-world test case, this led to a ~10x performance boost wrt. time spent in the `Comparator` code.
- Before this PR, sorting a `Stream` of `8520` items with this `Comparator` took `1455 ms`.
- As of this PR, sorting the same `Stream` took merely `150 ms`.
As a result, in the auto-complete input element of the aforementioned real-world test case, the overall time to find matches could by cut short by ~65%.
> PLAT-1238-1 DomAutoCompleteMatchEntryComparator: Cache normalization results

- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/matching/DomAutoCompleteMatchesBuilder.java
In a real-world test case, adding the `Set` field resulted in the total time spent in `DomAutoCompleteMatchesBuilder.addMatches` (while processing a single DOM event) being reduced from `4845ms` to `8ms`.
> PLAT-1238-2 DomAutoCompleteMatchesBuilder: Redundantly store known identifiers to improve performance

- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteInput.java
By no longer calling the expensive `DomAutoCompleteValueParser.parse` method but instead reusing the value-and-state cache in `DomAutoCompleteInput.deduceValue`, the following effects were achieved in a real-world test case, while processing a single DOM event:
- The total time consumption across 16 combined calls to `deduceValue()` and `getValue()` could be reduced from `1050ms` to `534ms` (i.e. cut by `49%`).
- Only one of those 16 combined calls resulted in a `DomAutoCompleteValueParser.parse` call.
> PLAT-1238-4 DomAutoCompleteInput: Reuse the cache for value and state in deduceValue()

- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteIndicator.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteInput.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteValueAndState.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteValueAndStateCache.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteValueParser.java
By reusing the value-and-state cache in `DomAutoCompleteIndicator`, the following effects were achieved in a real-world test case, while processing the creation of a complex input form, and a sequence of DOM event therein:
- The total time spent in `DomAutoCompleteValueParser.parse` could be reduced from `2700ms` to `677ms` (i.e. cut by `76%`).
- The total time spent to handle all DOM events was reduced from `8823ms` to `6677ms` (i.e. cut by `24%`).
Further notes:
- The value-and-state cache was extracted as top-level class `DomAutoCompleteValueAndStateCache`.
- The recent renaming was de-facto reverted, for now.
- Moved result handling to calling code. Particularly, the cache no longer throws.
- As of this PR, `DomAutoCompleteValueParser.parse` is exclusively called from within …
> PLAT-1238-5 DomAutoCompleteInput: Reuse the value-and-state cache for DomAutoCompleteIndicator

- platform-common/src/main/java/com/softicar/platform/common/string/normalizer/DiacriticNormalizer.java
- platform-common/src/test/java/com/softicar/platform/common/string/normalizer/DiacriticNormalizerTest.java
In a real-world test case, `DiacriticNormalizer` was used to normalize 1,474,839 strings.
- Before this PR, it took `2656ms`.
- With this PR, it took `920ms` (i.e. cut by `65%`).
The following measures were applied:
- Use a statically-precompiled pattern.
- Use a different conjunction of (1) normalization form and (2) pattern - which is apparently more efficient.
- Remove custom decomposition mappings.
- Proper handling of esoteric characters which are irrelevant to our current use cases is not worth a hefty performance impact.
- We solely rely on Unicode decomposition mappings now.
> PLAT-1238-6 Speed up DiacriticNormalizer

- platform-common/src/main/java/com/softicar/platform/common/string/normalizer/CurrentDiacriticNormalizationCache.java
- platform-common/src/main/java/com/softicar/platform/common/string/normalizer/DiacriticNormalizationCache.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/page/PageHeaderAndContentDiv.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteDisplayStringDeduplicator.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/matching/DomAutoCompleteMatchEntryComparator.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/matching/DomAutoCompleteMatcher.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/EmfAttributeByTitleComparator.java
This PR had the following effect in a real-world test case of creating a complex and partially pre-filled input form:
- The total amount of time spent in `DomAutoCompleteDisplayStringDeduplicator.apply` was reduced from `1213ms` to `615ms` (i.e. cut by `49%`).
- The total amount of time to display said input form was equally reduced.
> PLAT-1238-7 Create a singleton cache for diacritic normalization

- platform-dom/build.gradle
- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteDisplayStringDeduplicator.java
- platform-dom/src/test/java/com/softicar/platform/dom/elements/input/auto/AbstractDomAutoCompleteDefaultInputEngineTest.java
- platform-dom/src/test/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteDisplayStringDeduplicatorTest.java
Ordering the results was pointless because they will be re-ordered anyway, in all use cases of `DomAutoCompleteDisplayStringDeduplicator`. Using a pressimistically pre-sized `HashMap` yielded further performance benefits.
This PR had the following effect in a real-world test case of creating a complex and partially pre-filled input form:
- The total amount of time spent in `DomAutoCompleteDisplayStringDeduplicator.apply` was reduced from `542ms` to `369ms` (i.e. cut by `32%`).
> PLAT-1238-8 DomAutoCompleteDisplayStringDeduplicator: No longer order the results

- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteDefaultInputEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/foreign/entity/input/AbstractEmfEntityInputEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/table/configuration/EmfTableConfiguration.java
- platform-emf/src/main/java/com/softicar/platform/emf/table/configuration/IEmfTableConfiguration.java
This PR had the following effect in a real-world test case of creating a complex and partially pre-filled input form:
- The total amount of time spent to determine the display strings of values was reduced from `281ms` to `87ms` (i.e. cut by `69%`).
> PLAT-1238-9 Implement table-based deactivation of input-related display string deduplication

- platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteDefaultInputEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/foreign/entity/input/AbstractEmfEntityInputEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/table/configuration/EmfTableConfiguration.java
- platform-emf/src/main/java/com/softicar/platform/emf/table/configuration/IEmfTableConfiguration.java
Revert `PLAT-1238-9 Implement table-based deactivation of input-related display string deduplication (#610)` due to design concerns.
> PLAT-1238-10 Revert "PLAT-1238-9 Implement table-based deactivation of input-related display string deduplication (#610)"

- platform-dom/src/main/java/com/softicar/platform/dom/elements/AbstractDomCell.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/DomChildElementFinder.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/IDomCell.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/IEmfDataTableActionCell.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/element/TableExportChildElementFetcher.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/element/TableExportNamedDomCell.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/AbstractTableExportColumnFilteringEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/model/TableExportColumnModelFetcher.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/model/TableExportTableModel.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/spanning/TableExportSpanFetcher.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/spanning/element/TableExportSpanningCell.java
Table headers are now correctly positioned above their respective data columns. This was a regression since `EmfDataTableRow.ActionCell` no longer extended `AbstractDomCell`, due to [PLAT-1053](https://github.com/softicar/platform/pull/398).
Notes:
The empty leading column will be removed in an upcoming PR. That issue already existed before the regression which is fixed here. Particularly, we always had an empty leading column in table exports since we stopped captioning the first column with "Actions".
> EXP-2296 Table export: Fix misalignment of header and body columns

- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/AbstractTableExportColumnFilteringEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/AbstractTableExportEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/AbstractTableExportSubdividedEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/spanning/algorithm/TableExportSpanningElementColumnFilterer.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/util/TableExportLib.java
- Simplified non-null assertions.
- Removed timing log code.
- Removed some orphaned code.
- Fixed some variable names.
> EXP-2296-2 Table export: Basic code cleanup

- platform-dom/src/main/java/com/softicar/platform/dom/DomI18n.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/AbstractTableExportEngine.java
Upon table export failures, and before this PR, we tried really hard to show well-translated but totally technical and overly specific exception messages to users, about which they could do absolutely nothing.
Also, there were scenarios in which we only showed the fallback exception message.
This was simplified and unified, such that now merely show "Table export failed." to the user when anything goes wrong.
> EXP-2296-5 Table export: Simplify exception handling

- platform-emf/src/main/java/com/softicar/platform/emf/data/table/EmfDataTableDiv.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/IEmfDataTableDiv.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/column/selection/TableExportColumnSelectionButton.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/column/selection/TableExportColumnSelectionPopup.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/column/selection/TableExportColumnSelectionTableDiv.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/ITableExportNodeConverter.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/TableExportTypedNodeConverter.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/factory/ITableExportNodeConverterFactory.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/factory/TableExportDefaultNodeConverterFactory.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/factory/TableExportNodeConverterFactoryValueSelectBuilder.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/factory/TableExportNodeConverterFactoryWrapper.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/factory/TableExportStrictNodeConverterFactory.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/factory/TableExportTextOnlyNodeConverterFactory.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/factory/configuration/TableExportNodeConverterFactoryConfiguration.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/conversion/factory/selection/TableExportNodeConverterFactorySelectionModel.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/AbstractTableExportEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/ITableExportEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/configuration/TableExportColumnConfiguration.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/configuration/TableExportTableConfiguration.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/factory/AbstractTableExportEngineFactory.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/factory/ITableExportEngineFactory.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/implementation/csv/TableExportCsvEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/implementation/excel/TableExportExcelEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/implementation/html/TableExportHtmlEngine.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/model/TableExportColumnModelFetcher.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/popup/ITableExportPopupOptionsProvider.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/popup/TableExportPopupConfigurationInputForm.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/popup/TableExportPopupExecuteExportButton.java
Removed the `CT` "content type" type parameter from all table export classes, for the sake of simplicity.
The rationale behind that thing ceased to exist approx. 9 yrs ago.
> EXP-2296-6 Table export: Eliminate a superfluous type argument

- platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/engine/AbstractDomTestExecutionEngineLazySetup.java
- When a maximized popup is displayed, the other contents are disappended from the respective `IDomPopupContext`.
- In UI tests, that means that all nodes are disappended from the body, including the node-under-test.
- `IDomNodeTesterFindMethods.findBody()` uses `AbstractDomTestExecutionEngineLazySetup.getBodyNode()` which would hence, when a maximized popup is displayed in a test, return `null`. This in turn causes all sorts of things to crash.
This PR remedies that issue by changing `AbstractDomTestExecutionEngineLazySetup` such that we persistently remember the parent of the node-under-test during `initializeNode()`, for later retrieval via `getBodyNode()`.
> PLAT-1269 Avoid dynamic determination of body node

- platform-core-module/src/main/java/com/softicar/platform/core/module/user/profile/UserProfileChangeLocalizationDiv.java
- platform-dom/src/main/java/com/softicar/platform/dom/DomCssClasses.java
- platform-dom/src/main/java/com/softicar/platform/dom/elements/checkbox/DomCheckboxGroup.java
- platform-dom/src/main/resources/com/softicar/platform/dom/dom-checkbox-style.css
- platform-dom/src/test/java/com/softicar/platform/dom/elements/checkbox/DomCheckboxGroupTest.java
Auto-Complete inputs are just not suited to choose among a small number of well-known options.
This PR therefore implements "Radio Button"-style checkbox groups, as an `IDomValueInput`.
While this already benefits the localization selector (as shown in the GIF below), the same kind of input will be required for a subsequent PR in this series.
**After this PR:**
**Before this PR:**
> PLAT-1260-3 Implement DomCheckboxGroup

- build.gradle
`1.13.1` had the following vulnerabilities:
**Direct vulnerabilities:**
[CVE-2022-36033](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-36033)
[CVE-2021-37714](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37714)
**Vulnerabilities from dependencies:**
[CVE-2022-25647](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25647)
[CVE-2021-34428](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-34428)
[CVE-2020-27223](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-27223)
[CVE-2020-27218](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-27218)
> PLAT-1273 Upgrade jsoup to 1.15.3

- build.gradle
`4.1.77.Final` had the following vulnerabilities:
**Direct vulnerabilities:**
[CVE-2022-41915](https://ossindex.sonatype.org/vulnerability/CVE-2022-41915?component-type=maven&component-name=io.netty%2Fnetty-codec&utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0)
[sonatype-2020-0026](https://ossindex.sonatype.org/vulnerability/sonatype-2020-0026?component-type=maven&component-name=io.netty%2Fnetty-handler&utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0)
> PLAT-1275 Upgrade netty to 4.1.86.Final

- platform-common/src/main/java/com/softicar/platform/common/container/data/table/DataTableIdentifier.java
- platform-common/src/main/java/com/softicar/platform/common/container/data/table/IDataTable.java
- platform-common/src/main/java/com/softicar/platform/common/container/matrix/data/table/MatrixDataTable.java
- platform-common/src/test/java/com/softicar/platform/common/container/data/table/in/memory/AbstractInMemoryDataTableTest.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/component/external/ExternalComponentsPageNode.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/daemon/watchdog/state/DaemonWatchdogStatePageDiv.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/overview/StoredFileOverviewDataTable.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/module/overview/ModuleOverviewTable.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/module/overview/ModulePagesTable.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/user/session/UserSessionsTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/attribute/input/auto/complete/EmfAutoCompleteBrowseTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/configuration/EmfDataTableConfigurationTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/column/selection/TableExportColumnSelectionTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/entity/table/action/EmfTableActionOverviewTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/entity/table/attribute/EmfTableAttributeOverviewTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/entity/table/overview/EmfTableOverviewTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/log/viewer/table/EmfLogDataTable.java
- platform-emf/src/main/java/com/softicar/platform/emf/management/importing/submit/EmfImportSubmitDiv.java
- platform-emf/src/main/java/com/softicar/platform/emf/management/importing/upload/EmfImportUploadDiv.java
- platform-emf/src/main/java/com/softicar/platform/emf/management/importing/upload/EmfImportViewUploadedDataDiv.java
- platform-emf/src/main/java/com/softicar/platform/emf/management/importing/variable/replace/EmfImportViewDataWithReplacementsDiv.java
- platform-emf/src/main/java/com/softicar/platform/emf/module/permission/EmfModulePermissionViewTable.java
- platform-emf/src/test/java/com/softicar/platform/emf/data/table/TestDataTable.java
- platform-emf/src/test/java/com/softicar/platform/emf/data/table/TestTable.java
- platform-emf/src/test/java/com/softicar/platform/emf/data/table/configuration/EmfDataTableConfigurationPopupTest.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/item/message/WorkflowItemMessageDataTable.java
The default method led to silent failures to restore user-specific configurations, all over the place.
> PLAT-1276 IDataTable: Remove default implementation of getIdentifier()

- platform-core-module/src/main/java/com/softicar/platform/core/module/user/preferences/UserPreferences.java
- platform-core-module/src/test/java/com/softicar/platform/core/module/user/preferences/UserPreferencesManagerTest.java
- platform-core-module/src/test/java/com/softicar/platform/core/module/user/profile/UserProfilePreferencesDivTest.java
This fixes an unintended change in navigation folder collapsing default behavior, caused by #636 / `PLAT-1260-1`.
- Navigation folders will now collapse again by default, for new users.
- Note: Even before #636 the default values (`automatic=true` & `recursive=false`) were inconsistent, i.e. they specified the sole invalid combination of modes.
> PLAT-1267 Fix default navigation behavior

- platform-ajax/src/test/java/com/softicar/platform/ajax/dom/event/click/AjaxDomDoubleClickEventTest.java
`AjaxDomDoubleClickEventTest.test()` is racy for unknown reasons.
This must be a problem with the test setup, and we're currently heavily time-constrained. So we just manipulate the race for now.
> PLAT-1296 AjaxDomDoubleClickEventTest: Add a delay to avoid a non-determinism

- .classpath
- build.gradle
Avoid that Buildship messes with the root project classpath and JDT prefs upon Gradle builds.
> EXP-2518-3 Specifiy source compatibility level for the root project

- platform-common-ocr/src/main/java/com/softicar/platform/common/ocr/tesseract/TesseractOcrTextExtractor.java
- For Tesseract, we previously relied on the default which led to this warning upon each execution: `Warning: Invalid resolution 0 dpi. Using 70 instead.`. We now use an explicit and configurable DPI value which defaults to 120.
- For PDF rendering before the actual Tesseract run, we previously used 300 DPI. That was unnecessarily high and even led to subpar results. This is now configurable as well, with a default of 120.
Overall, a speedup of ~40% was observed, as well as an increase in overall result quality / precision.
> PLAT-1299 TesseractOcrTextExtractor: Explicitly define DPI values, and optimize defaults

- platform-common-ocr/src/main/java/com/softicar/platform/common/ocr/tesseract/TesseractOcrTextExtractor.java
- platform-common-ocr/src/main/java/com/softicar/platform/common/ocr/tesseract/TesseractPageSegmentationMode.java
- `TesseractPageSegmentationMode` now provides a subset of Tesseract's built-in segmentation mode options.
- i.e. those which neither produce completely garbled output nor crash the JVM.
- `TesseractPageSegmentationMode.PSM_SPARSE_TEXT` will be particularly useful for a current purpose in a derived project.
- Tesseract's internal default is `PSM_SINGLE_BLOCK`, so we default to that as well (principle of least surprise).
> PLAT-1305 TesseractOcrTextExtractor: Enable selection of page segmentation modes

- platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/AGMaintenanceWindowTable.java
- Order by `expected start`, descending. This way, most recent windows are on top.
- Add default values for `expected start` and `expected end`. This way, entering everything manually is no longer necessary.
> PLAT-1309 AGMaintenanceWindowTable: Improve Defaults

- platform-core-module/src/main/java/com/softicar/platform/core/module/email/converter/EmailToPdfConverter.java
Before this PR, XHTML-to-PDF conversion would fail if the XHTML contained tags like `<o:p>` while lacking corresponding namespace definitions in its `html` tag.
> EXP-2677 EmailToPdfConverter: Add Microsoft namespaces to intermediate XHTML if necessary

- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/WorkflowPredicates.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/management/WorkflowVersionManagementDiv.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/node/AGWorkflowNodeTable.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/node/action/AGWorkflowNodeActionTable.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/node/precondition/AGWorkflowNodePreconditionTable.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/AGWorkflowTransitionTable.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/permission/AGWorkflowTransitionPermissionTable.java
- platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersionTable.java
Removed the nuance that "finalized" workflows cant be edited in any way.
Reasoning: Permissions to edit and create are already set to Administrators, and they should know what to do.
> EXP-2827 Worfklow: Make finalized versions editable

- platform-emf/src/main/java/com/softicar/platform/emf/form/EmfFormBody.java
- platform-emf/src/main/java/com/softicar/platform/emf/form/EmfFormSaveOrCancelActionsInput.java
When using the Edit-Management-Action, the EmfFormPopup behaved slightly different
- There was no Save-Button, only Save & Close
Added the normal save button to direct editing mode
> EXP-2818 Remove EmfForm-directEditing nuances

- platform-core-module/src/main/java/com/softicar/platform/core/module/email/buffer/BufferedEmailSender.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/email/buffer/BufferedEmailSenderSessionManager.java
Added 30s timeouts:
- `mail.smtp.connectiontimeout`
- `mail.smtp.timeout`
- `mail.smtp.writetimeout`
> PLAT-1359 BufferedEmailSenderSessionManager: Use finite timeouts

- platform-core-module/src/main/java/com/softicar/platform/core/module/email/buffer/BufferedEmailSendProgram.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/email/buffer/BufferedEmailSender.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/email/buffer/BufferedEmailSenderSessionManager.java
- Before this PR, we set SMTP timeout properties as `long` values.
- A literal interpretation of the documentation at (https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html) implies that properties need to be set as String:
> The SMTP protocol provider supports the following properties, which may be set in the JavaMail Session object. The properties are always set as strings; the Type column describes how the string is interpreted.
Unrelated:
- Slightly improved log output.
> PLAT-1363 Set SMTP properties as String

- platform-core-module/src/main/java/com/softicar/platform/core/module/page/navigation/entry/PageNavigationEntriesLoader.java
**Test Plan**: Connect EAS and observe reduced number of executed SELECT statements.
Before:
```
[   149ms,    7x] SELECT t.`id`, t.`moduleInstance`, t.`name`, t.`active` FROM `Invoice`.`InvoiceGroup` t WHERE t.`active` AND (t.`moduleInstance` IN (?)) ORDER BY t.`id`
```
After:
```
[    23ms,    1x] SELECT t.`id`, t.`moduleInstance`, t.`name`, t.`active` FROM `Invoice`.`InvoiceGroup` t WHERE t.`active` AND (t.`moduleInstance` IN (?,?,?,?,?,?,?)) ORDER BY t.`id`
```
> PLAT-1402 Module Data Prefetching by PageNavigationEntriesLoader

- platform-common/src/main/java/com/softicar/platform/common/core/i18n/I18nKeyDisplayString.java
- platform-common/src/main/java/com/softicar/platform/common/core/i18n/key/AbstractI18nKey.java
- platform-common/src/main/java/com/softicar/platform/common/core/i18n/key/II18nKey.java
- platform-common/src/main/java/com/softicar/platform/common/core/i18n/key/container/validator/I18nKeyContainerFieldValueValidator.java
- added new `default` translation thats set when creating the key
- the `default` value is used as a basis for checking I18n-Field-Names in the validator
- added `.en` method to enable changing of English translation
> PLAT-1398 Add en-overwrite for I18n-Keys

- platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/AGProgramExecution.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/IProgramExecutionsQuery.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/ProgramExecutionPage.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/ProgramExecutionsDiv.java
- platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/ProgramExecutionsQuery.sqml
If there are too many records or the records consume too much memory (column `ProgramExecution.output` is of type "longtext"!), you will get `OutOfMemoryError`!
**Stacktrace:**
```
java.lang.OutOfMemoryError: Java heap space
at java.base/java.lang.String.<init>(String.java:568)
at org.mariadb.jdbc.internal.com.read.resultset.rowprotocol.TextRowProtocol.getInternalString(TextRowProtocol.java:240)
at org.mariadb.jdbc.internal.com.read.resultset.SelectResultSet.getString(SelectResultSet.java:948)
at com.softicar.platform.db.core.DbResultSet.getString(DbResultSet.java:267)
at com.softicar.platform.db.sql.type.SqlStringType.getValue(SqlStringType.java:16)
at com.softicar.platform.db.sql.type.SqlStringType.getValue(SqlStringType.java:11)
at …
```
> EXP-3130: Fix OutOfMemoryError in ProgramExecutionPage
