README.md

- Referred to Semantic Versioning, and added examples.
- Unrelated: Swapped the latter two sections, added section numbers, and fixed some capitcalization.

PLAT-555 Add 'Releases and Versioning' section

---

platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/server/AGStoredFileServerTable.java

- set password mode for the attribute in the table class﻿

PLAT-523 Fix AGStoredFileServerTable Password Display

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/execution/auto/WorkflowAutoTransitionExecutor.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/program/WorkflowAutoTransitionExecutionProgram.java
platform-workflow-module/src/test/java/com/softicar/platform/workflow/module/workflow/transition/execution/auto/WorkflowAutoTransitionExecutorTest.java

- extracted code from WorkflowAutoTransitionExecutionProgram in WorkflowAutoTransitionExecutor to be used seperately
- added some checks in WorkflowAutoTransitionExecutor for manual use
- added test for WorkflowAutoTransitionExecutor﻿

PLAT-544 Extracted WorkfowAutoTransitionExecutor & Tests

---

platform-dom/src/main/java/com/softicar/platform/dom/elements/tables/pageable/navigation/GoToPagePopup.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/engine/IDomTestEngine.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/engine/document/DomDocumentTestEngine.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/node/tester/AbstractDomNodeTester.java
platform-dom/src/main/java/com/softicar/platform/dom/event/DomEventType.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomEventHandler.java
platform-emf/src/test/java/com/softicar/platform/emf/data/table/EmfDataTablePagingTest.java

- adapted some tests in `EmfDataTablePagingTest`
- fixed event handler implementation in `GoToPagePopup`
- simplified event sending in `DomDocumentTestEngine`

PLAT-543 DomDocumentTestEngine.setInputValue() Now Triggers TAB Event

---

README.md

- Move some information to `README.md` in the example project.
- Clearly and prominently refer to the example project.
- Move `Releases and Versioning` to the bottom.

PLAT-575 Improve README.md

---

platform-demo-module/src/test/java/com/softicar/platform/demo/module/invoice/transients/DemoInvoicesTransientFieldFilteringTest.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/number/decimal/DomBigDecimalInput.java
platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/bigdecimal/EmfBigDecimalAttribute.java
platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/bigdecimal/EmfBigDecimalInput.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/value/EmfDataTableValueFilter.java

- automated testing: extended `DemoInvoicesTransientFieldFilteringTest`
- manual testing: open the DemoInvoicePage and test filtering

PLT-567 Replaced Dubious BigDecimal Scaling and Formatting

---

platform-emf/src/main/java/com/softicar/platform/emf/editor/EmfEditAction.java

Click the Edit Action multiple time in any EmfManagementDiv and verify that only a single Popup is ever open

PLAT-449 Use DomPopupManager in EmfEditAction

---

platform-core-module/src/main/java/com/softicar/platform/core/module/test/fixture/CoreModuleTestFixtureMethods.java

PLAT-595 Add method insertServer() to CoreModuleTestFixtureMethods

---

platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-button-style.css

PLAT-620 Fix horizontal alignment of button labels

---

platform-core-module/src/main/java/com/softicar/platform/core/module/uuid/AGUuid.java

* FIXME was added
* Test Plan: Just view the change﻿

PLAT-615 Show Role Names, Not UUIDs

---

platform-core-module/src/main/java/com/softicar/platform/core/module/uuid/AGUuidTable.java

PLAT-614 Conceal UUID-Bytes in UUID Page

---

platform-core-module/src/main/java/com/softicar/platform/core/module/access/module/instance/ModuleInstancePredicates.java
platform-core-module/src/main/java/com/softicar/platform/core/module/access/module/instance/actions/ModuleInstanceInitializationAction.java

PLAT-607 Add Active Condition to Module Init Action

---

platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-bar-style.css
platform-emf/src/main/resources/com/softicar/platform/emf/emf-form-section-style.css

PLAT-627 Fix some layout direction issues

---

platform-emf/src/main/resources/com/softicar/platform/emf/emf-input-style.css

PLAT-632 Fix Password Input Eye Alignment

---

platform-core-module/src/main/java/com/softicar/platform/core/module/user/notification/UsersNotificationPageDiv.java

PLAT-625 Change default FROM address in user notification

---

platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/user/password/UserPasswordGenerator.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/DomElementsCssClasses.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/dialog/DomModalAlertPopup.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/dialog/DomModalConfirmPopup.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/dialog/DomModalPromptPopup.java
platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-modal-dialog-style.css

PLAT-637 Show Password in Popup after reset

---

platform-core-module/src/main/java/com/softicar/platform/core/module/email/EmailDumper.java
platform-core-module/src/main/java/com/softicar/platform/core/module/email/EmailSystemProperties.java
platform-core-module/src/main/java/com/softicar/platform/core/module/email/buffer/BufferedEmailSender.java

PLAT-633 Fix dumping for buffered emails

---

platform-emf/src/main/resources/com/softicar/platform/emf/emf-form-style.css

Reverted some changes from #95

PLAT-642 Fix DomButton Style in EmfFormSectionContentDiv

---

platform-core-module/src/main/java/com/softicar/platform/core/module/page/PageHeaderDiv.java

URL when logged in
After Logging Out

PLAT-641 Change URL when Logging out

---

platform-common-core/src/main/java/com/softicar/platform/common/core/properties/AbstractProperty.java
platform-common-core/src/test/java/com/softicar/platform/common/core/properties/AbstractPropertyTest.java

PLAT-645 Fix Properties not Trimming their Values

---

platform-ajax/build.gradle

Report without this PR: https://sbom.lift.sonatype.com/report/T1-0ff0976f7f21c391f20f-524841b7555ac9-1643381300-3aa288d9867a4691a8e55a4360a34374
Report with this PR: https://sbom.lift.sonatype.com/report/T1-0ff0976f7f21c391f20f-524841b7555ac9-1643382384-92d1d13115da4008a301384bf33f637e

PLAT-628 Avoid a false-positive in Sonatype Lift

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/IWorkflowTaskQuery.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskDiv.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskQuery.sqml

PLAT-664 Fix translation in WorkflowTaskPage column titles

---

platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramValidator.java

PLAT-680 Fix NPE in ProgramsPage, if Nothing Is Entered in Input Field "Execution Retention Days"

---

platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/table/configuration/DbTableConfigurationCodeValidator.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/WorkflowTransitionActionFactory.java

We erroneously omitted that in the platform, so far.

PLAT-684 Create a code validator for all table configurations

---

platform-core-module/src/main/java/com/softicar/platform/core/module/access/module/instance/ModuleInstanceTitleField.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/column/handler/filtering/EmfDataTableColumnFilterNodeFactoryMap.java

PLAT-679 Make AGModuleInstance.TITLE filterable

---

platform-dom/src/main/java/com/softicar/platform/dom/event/upload/IDomFileUpload.java
platform-emf/src/main/resources/com/softicar/platform/emf/emf-form-style.css

PLAT-703: Fix EmfFormPopup display with additional content

---

platform-dom/src/main/java/com/softicar/platform/dom/input/auto/DomAutoCompleteList.java

PLAT-686 Extends auto complete entries to 16

---

platform-core-module/src/main/java/com/softicar/platform/core/module/page/navigation/PageNavigationFolderController.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/navigation/PageNavigationPageController.java
platform-core-module/src/test/java/com/softicar/platform/core/module/page/PageDivTest.java

PLAT-700 Remove Automatic Folder Closing in Navigation

---

platform-ajax/src/main/java/com/softicar/platform/ajax/engine/AjaxDomEngine.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/PageHeaderAndContentDiv.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/service/PageServiceDocumentBuilder.java
platform-dom/src/main/java/com/softicar/platform/dom/engine/DomNullEngine.java
platform-dom/src/main/java/com/softicar/platform/dom/engine/IDomEngine.java
platform-dom/src/main/java/com/softicar/platform/dom/input/auto/DomAutoCompleteList.java

PLAT-699 Update tab title when changing pages

---

platform-demo-module/src/main/java/com/softicar/platform/demo/module/DemoI18n.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/AGDemoInvoiceTable.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/DemoInvoiceCreationPopup.java
platform-demo-module/src/test/java/com/softicar/platform/demo/module/instance/creation/DemoModuleInstanceCreationTest.java
platform-demo-module/src/test/java/com/softicar/platform/demo/module/invoice/DemoInvoiceCreationPopupTest.java
platform-demo-module/src/test/java/com/softicar/platform/demo/module/moment/DemoMomentInputTest.java
platform-emf/src/main/java/com/softicar/platform/emf/management/EmfManagementDiv.java
platform-emf/src/main/java/com/softicar/platform/emf/table/configuration/EmfTableConfiguration.java
platform-emf/src/main/java/com/softicar/platform/emf/table/configuration/IEmfTableConfiguration.java
platform-emf/src/main/java/com/softicar/platform/emf/test/tester/EmfManagementDivTester.java
platform-emf/src/test/java/com/softicar/platform/emf/form/derived/EmfFormForObjectWithDerivedValueTest.java

- PLAT-704 Added Support for Custom Creation Popups
- PLAT-704 Added Test for Custom Creation Popups

PLAT-704 Support for EMF Custom Creation Popups

---

platform-ajax/src/main/java/com/softicar/platform/ajax/AjaxI18n.java
platform-ajax/src/main/java/com/softicar/platform/ajax/document/creation/AjaxDocumentPagePrinter.java
platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/engine/level/low/AjaxSeleniumLowLevelTestEngineAutoCompleteExtension.java
platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/engine/level/low/interfaces/IAjaxSeleniumLowLevelTestEngineAutoCompleteExtension.java
platform-ajax/src/main/resources/com/softicar/platform/ajax/ajax-style.css
platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/auto/complete/AutoCompletePopup.js
platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/AbstractAjaxAutoCompleteTest.java
platform-ajax/src/test/java/com/softicar/platform/ajax/input/auto/complete/AjaxAutoCompleteTest.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteInput.java
platform-dom/src/main/java/com/softicar/platform/dom/input/auto/DomAutoCompleteList.java

PLAT-687 Add more Items info to AutoCompleteInputs

---

platform-emf/src/main/java/com/softicar/platform/emf/EmfImages.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/configuration/EmfDataTableConfigurationPopup.java
platform-emf/src/main/resources/com/softicar/platform/emf/reset.svg

The "Reset icon" must be different from the "Refresh icon".

PLAT-254 New Reset Icon

---

platform-demo-module/src/main/java/com/softicar/platform/demo/module/DemoI18n.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/AGDemoInvoice.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/AGDemoInvoice.sqml
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/AGDemoInvoiceGenerated.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/AGDemoInvoiceTable.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/DemoInvoicePredicates.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/type/AGDemoInvoiceType.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/type/AGDemoInvoiceType.sqml
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/type/AGDemoInvoiceTypeEnum.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/invoice/type/AGDemoInvoiceTypeGenerated.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/test/fixture/DemoInvoicesTestFixture.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/test/fixture/DemoModuleTestFixture.java
platform-demo-module/src/main/java/com/softicar/platform/demo/module/test/fixture/DemoModuleTestFixtureMethods.java
platform-demo-module/src/test/java/com/softicar/platform/demo/module/invoice/importing/DemoInvoiceImportTest.java
platform-demo-module/src/test/java/com/softicar/platform/demo/module/invoice/item/lock/DemoInvoiceItemLockTest.java
platform-demo-module/src/test/java/com/softicar/platform/demo/module/invoice/stale/StaleDemoInvoiceRefreshTest.java
platform-demo-module/src/test/java/com/softicar/platform/demo/module/invoice/transients/DemoInvoicesTransientFieldFilteringTest.java
platform-demo-module/src/test/java/com/softicar/platform/demo/module/invoice/transients/DemoInvoicesTransientFieldSortingTest.java
platform-emf/src/main/java/com/softicar/platform/emf/editor/EmfAttributesDiv.java
platform-emf/src/main/java/com/softicar/platform/emf/form/EmfFormAttributesDiv.java
platform-emf/src/main/java/com/softicar/platform/emf/token/parser/converter/EmfTokenToForeignConverter.java

- extended AGDemoInvoice
- simplified EmfAttributesDiv (removed useless methods)

PLAT-730-1 Simplified EmfAttributesDiv and Extended AGDemoInvoice

---

platform-dom/src/main/java/com/softicar/platform/dom/document/IDomDocument.java
platform-dom/src/main/java/com/softicar/platform/dom/element/DomDelegatingElement.java
platform-dom/src/main/java/com/softicar/platform/dom/element/DomElement.java
platform-dom/src/main/java/com/softicar/platform/dom/element/DomElementTag.java
platform-dom/src/main/java/com/softicar/platform/dom/element/IDomElement.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/button/popup/help/DomHelpPopupButton.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomChangeEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomClickEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomContextMenuEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomDoubleClickEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomEnterKeyEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomEscapeKeyEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomKeyPressEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomSpaceKeyEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomTabKeyEventHandler.java
platform-dom/src/main/java/com/softicar/platform/dom/node/AbstractDomNode.java
platform-dom/src/main/java/com/softicar/platform/dom/node/DomDelegatingNode.java
platform-dom/src/main/java/com/softicar/platform/dom/node/DomNode.java
platform-dom/src/main/java/com/softicar/platform/dom/node/IDomNode.java
platform-dom/src/main/java/com/softicar/platform/dom/parent/DomParentElement.java
platform-dom/src/main/java/com/softicar/platform/dom/text/DomTextNode.java
platform-dom/src/test/java/com/softicar/platform/dom/elements/wiki/DomWikiDivBuilderTest.java
platform-dom/src/test/java/com/softicar/platform/dom/node/AbstractDomNodeTest.java

- removed IDomElement HTML building features
- removed unused IDomElement.replaceWith method
- removed DomElement.HierarchyType
- fixed DomWikiDivBuilderTest to use DOM test engine
- removed DomNode

PLAT-806 Cleanup of IDomElement

---

platform-core-module/src/main/resources/com/softicar/platform/core/module/page/page-style.css

PLAT-811 Remove redundant shadow below page header

---

platform-core-module/src/main/java/com/softicar/platform/core/module/user/AGUserTable.java
platform-core-module/src/main/java/com/softicar/platform/core/module/user/navigation/RecursivelyCollapseFoldersInput.java

PLAT-810 Adapt recursive folder collapsing configuration

---

platform-ajax/src/main/java/com/softicar/platform/ajax/AjaxI18n.java
platform-ajax/src/main/java/com/softicar/platform/ajax/engine/elements/AjaxSessionTimeoutDialog.java
platform-ajax/src/main/java/com/softicar/platform/ajax/engine/elements/AjaxSessionTimeoutDialogMessage.java
platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/engine/level/low/AjaxSeleniumLowLevelTestEngineInput.java
platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/engine/level/low/interfaces/IAjaxSeleniumLowLevelTestEngineInput.java
platform-ajax/src/main/java/com/softicar/platform/ajax/testing/selenium/engine/level/low/interfaces/IAjaxSeleniumLowLevelTestEngineMethods.java
platform-ajax/src/main/resources/com/softicar/platform/ajax/ajax-style.css
platform-ajax/src/test/java/com/softicar/platform/ajax/session/timeout/AjaxSessionTimeoutTest.java
platform-common/src/main/java/com/softicar/platform/common/core/CommonCoreI18n.java

PLAT-855 Adapt SessionTimeoutDialogMessage

---

platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/service/login/PageServiceLoginDiv.java

PLAT-808-6 Adapt Maintenance Info Display

---

platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/session/SessionOverviewPageDiv.java

PLAT-873 Session Overview: Add 'Refresh' button

---

platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/session/SessionsPageDiv.java
platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/session/SessionsTable.java

- Use FK popup buttons.
- Show a placeholder when the user is unknown.

PLAT-879 Sessions Page: Improve user column

---

platform-dom/src/main/java/com/softicar/platform/dom/elements/select/value/simple/display/DomSimpleValueSelectDefaultValueComparator.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/configuration/EmfDataTableConfigurationTableDiv.java

PLAT-864 Set proper comparator for column drop-down

---

platform-common/src/main/java/com/softicar/platform/common/container/CommonContainerI18n.java
platform-common/src/main/java/com/softicar/platform/common/container/data/table/DataTableValueFilterOperator.java
platform-common/src/main/java/com/softicar/platform/common/container/data/table/in/memory/InMemoryDataTableValueFilter.java
platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/data/table/DbTableBasedDataTableValueFilter.java
platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/query/filters/DbQueryValueFilter.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/EmfDataTableI18n.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/entity/EmfDataTableEntityFilterNode.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/entity/EmfDataTableEntityFilterType.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/entity/EmfDataTableEntityFilterTypeSelect.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/string/EmfDataTableStringFilterInput.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/string/EmfDataTableStringFilterNode.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/string/EmfDataTableStringFilterType.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/string/EmptyTextFilter.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/string/NotEmptyTextFilter.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/value/EmfDataTableEmptyValueFilter.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/value/EmfDataTableNotEmptyValueFilter.java
platform-emf/src/test/java/com/softicar/platform/emf/data/table/EmfDataTableFilterByEntityTest.java
platform-emf/src/test/java/com/softicar/platform/emf/data/table/EmfDataTableFilterByStringTest.java

- Table (Note: unknown is displayed if the value is null)

PLAT-871 Added Empty/Not-Empty to EmfDataTableValueFilter

---

platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/service/login/PageServiceLoginDiv.java

PLAT-903 Show pending maintenance info in login page

---

platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/ProgramExecutionRunnable.java

PLAT-837 Create system event for failed programs

---

platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/string/EmfPasswordInput.java
platform-emf/src/main/resources/com/softicar/platform/emf/emf-input-style.css

PLAT-912 Change style of EmfPasswordInput

---

platform-core-module/src/main/java/com/softicar/platform/core/module/ajax/exception/AGAjaxException.java
platform-core-module/src/main/java/com/softicar/platform/core/module/ajax/exception/AGAjaxException.sqml
platform-integration/src/main/resources/com/softicar/platform/integration/database/structure/version/v20-structure.json

Added cascade on delete to AGAjaxException to prevent foreign key constraint failure

PLAT-953 Fix CoreLogRecordCleanupProgram

---

platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/auto/complete/AutoCompleteInputContext.js
platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/auto/complete/AutoCompletePopup.js
platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/auto/complete/AutoCompleteUtils.js

PLAT-955 Fix AutoCompletePopup positioning

---

platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/PageDiv.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/navigation/PageNavigationPageController.java

PLAT-1006 Improved Handling of Non-Existing Pages

---

platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/entity/DomAutoCompleteEntityInMemoryInputEngine.java
platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/foreign/entity/input/engine/AbstractEmfDependentAutoCompleteInputEngine.java

PLAT-1001 Eagerly refresh the cache when refreshing an input engine

---

platform-ajax/src/main/resources/com/softicar/platform/ajax/ajax-style.css
platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/module/instance/actions/ModuleInstanceInitializationAction.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/navigation/PageNavigationPageController.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/ProgramExecutionRunnable.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/entity/DomAutoCompleteEntityInMemoryInputEngine.java
platform-emf/src/main/java/com/softicar/platform/emf/attribute/field/foreign/entity/input/engine/AbstractEmfDependentAutoCompleteInputEngine.java

- PLAT-1003 Failing Program Executions Are Now Errors Not Warnings (#340)
- PLAT-999 Fix Handling of not-accessible Page-Parameters (#344)
- PLAT-1000 Fix duplicatable popups in Module Instances page (#346)
- PLAT-1001 Eagerly refresh the cache when refreshing an input engine (#350)
- PLAT-1007 Fix font color in auto-complete popover if input is in error state (#352)

v20 backport batch

---

platform-core-module/src/main/java/com/softicar/platform/core/module/module/instance/actions/ModuleInstanceInitializationAction.java

PLAT-1021 Ensure that 'initialize module instance' popup remains accessible

---

platform-dom/src/main/java/com/softicar/platform/dom/elements/DomElementsCssClasses.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/label/DomLabelGrid.java
platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-input-diagnostics-style.css
platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-label-grid-style.css

**Firefox 102.0:**
**Chromium 103.0:**
**Safari 14.1.2:**

PLAT-993 Add row highlighting to DomLabelGrid

---

platform-dom/src/main/resources/com/softicar/platform/dom/elements/dom-pageable-table-style.css

PLAT-1031 Hide DomPageableTableNavigation when empty

---

platform-core-module/src/main/java/com/softicar/platform/core/module/container/docker/DockerContainerController.java
platform-core-module/src/test/java/com/softicar/platform/core/module/file/smb/jcifsng/AbtractJcifsNgSmbTest.java

- Implemented fully flexible support for run-options (i.e. options passed to the `docker run` command).
- Can now handle containers which don't provide health state.

PLAT-977-2 Refactor DockerContainerController

---

platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/auto/complete/AutoCompleteUtils.js

PLAT-1051 Fix horizontal truncation of auto-complete popover

---

platform-core-module/src/main/java/com/softicar/platform/core/module/CoreCssClasses.java
platform-core-module/src/main/java/com/softicar/platform/core/module/CoreCssFiles.java
platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/MaintenanceWindowsInfoElement.java
platform-core-module/src/main/java/com/softicar/platform/core/module/start/page/StartPageDiv.java
platform-core-module/src/main/resources/com/softicar/platform/core/module/maintenance-window-style.css

PLAT-1049 Beautify 'Pending Maintenance' info element

---

platform-core-module/src/main/resources/com/softicar/platform/core/module/page/navigation/page-navigation-style.css

PLAT-1040 Fix vertical alignment of navigation logo

---

platform-core-module/src/main/java/com/softicar/platform/core/module/module/overview/ModuleOverviewPageDiv.java
platform-emf/src/main/java/com/softicar/platform/emf/management/AbstractEmfManagementActionPopover.java
platform-emf/src/main/java/com/softicar/platform/emf/management/EmfManagementActionPopover.java

PLAT-985 Fix alignment of actions in module classes page

---

platform-core-module/src/main/java/com/softicar/platform/core/module/AGCoreModuleInstance.java
platform-emf/src/main/java/com/softicar/platform/emf/entity/table/IEmfEntityTable.java
platform-emf/src/main/java/com/softicar/platform/emf/sub/object/table/EmfSubObjectTable.java

Processed a `TODO` that referenced a legacy issue. Turned out straightforward.

PLAT-1081-2 IEmfEntityTable: Remove "E get(Integer)"

---

platform-dom/src/main/java/com/softicar/platform/dom/input/DomSelect.java

- Legacy issue references to `i42633` and `i48744` were removed - retention seemed pointless.
- Also refactored most of the comments in this class.

PLAT-1081-1 Update comments in DomSelect

---

build.gradle

The latest release in the 4.2.x series.

PLAT-1114 Upgrade selenium to 4.2.2

---

platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramMaintenanceMessageBar.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramMaintenanceMessageDiv.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/ProgramPage.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/QueuedProgramExecutionDaemon.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/ProgramExecutionPage.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/scheduled/ScheduledProgramExecutionPage.java
platform-core-module/src/test/java/com/softicar/platform/core/module/program/QueuedProgramExecutionDaemonTest.java

- Info message will be shown in `Program Executions`, `Programs` and `Scheduled Program Executions`

PLAT-1108 No program execution during maintenance

---

README.md

Add some shields

---

platform-ajax/.settings/org.moreunit.prefs
platform-common-excel/.settings/org.moreunit.prefs
platform-common/.settings/org.moreunit.prefs
platform-core-module/.settings/org.moreunit.prefs
platform-db-core/.settings/org.moreunit.prefs
platform-db-runtime/.settings/org.moreunit.prefs
platform-db-sql/.settings/org.moreunit.prefs
platform-db-structure/.settings/org.moreunit.prefs
platform-dom/.settings/org.moreunit.prefs
platform-emf/.settings/org.moreunit.prefs
platform-integration/.settings/org.moreunit.prefs
platform-workflow-module/.settings/org.moreunit.prefs

Omitted sub projects that do not have a `src/test/java` source directory.

PLAT-1138 Add project-specific MoreUnit settings

---

platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/structure/comparison/column/DbColumnStructureEqualityComparer.java
platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/structure/comparison/diagnostic/DbStructureComparisonDiagnostic.java
platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/structure/comparison/diagnostic/DbStructureComparisonDiagnosticContainer.java
platform-db-runtime/src/main/java/com/softicar/platform/db/runtime/structure/comparison/feature/checker/DbMutualFeatureChecker.java
platform-integration/src/main/java/com/softicar/platform/integration/database/structure/version/AbstractDatabaseStructureVersionMigrationsTest.java

PLAT-1158-2 Reformat DB structure comparer output

---

platform-ajax/src/main/java/com/softicar/platform/ajax/engine/AjaxDomEngine.java
platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/TypeScriptGenerated.js
platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/DragAndDrop.ts
platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/Math.ts
platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/Rect.ts
platform-ajax/src/test/java/com/softicar/platform/ajax/drag/and/drop/AjaxDragAndDropTest.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/image/viewer/DomImageViewerImageHolder.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/popup/DomPopupFrame.java
platform-dom/src/main/java/com/softicar/platform/dom/engine/DomNullEngine.java
platform-dom/src/main/java/com/softicar/platform/dom/engine/IDomEngine.java
platform-dom/src/main/resources/com/softicar/platform/dom/dom-image-viewer-style.css
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/management/display/element/WorkflowNodeDisplayElement.java

new feature: **scroll node**
no regression: **limit node** still working

PLAT-1147 Improved Dragging in DomImageViewer

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/management/display/line/WorkflowTransitionLine.java

PLAT-1178 Improved Routing of WorkflowTransitionLine for Self-References

---

platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteDefaultInputEngine.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompletePopupValueDisplay.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/pattern/MultiPatternMatch.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/pattern/MultiPatternMatchRange.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/pattern/MultiPatternMatcher.java
platform-dom/src/test/java/com/softicar/platform/dom/elements/input/auto/AbstractDomAutoCompleteDefaultInputEngineTest.java
platform-dom/src/test/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteDefaultInputEngineTest.java
platform-dom/src/test/java/com/softicar/platform/dom/elements/input/auto/pattern/MultiPatternMatcherTest.java
platform-emf/src/test/java/com/softicar/platform/emf/attribute/field/enums/table/row/EmfEnumTableRowInputEngineTest.java

PLAT-1033 Auto-complete inputs: Implement multi-pattern matching

---

platform-core-module/src/main/java/com/softicar/platform/core/module/environment/LiveSystemRevision.java

PLAT-1193 Fix revision version and id not showing

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/program/WorkflowAutoTransitionExecutionProgram.java

before:
was caused by unexpected exception by `toDisplayStringWithoutId`:
now fixed, code continues to execute after throwing `toDisplayStringWithoutId`

PLAT-1186 Improved Robustness of Auto-Transitions Executor

---

platform-ajax/src/main/resources/com/softicar/platform/ajax/ajax-style.css

PLAT-1207 Fix wrong cursor in AjaxSessionTimeoutDialogMessage

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/management/WorkflowVersionManagementPopup.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersion.java

Change workflow graph popup: Display version ID and type of version as sub-caption.
See how it will look:

EXP-2070 Workflow Module: Display Workflow's Version Number in Workflow Graph Popup

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/node/precondition/IWorkflowPrecondition.java

PLAT-1252 Include UUIDs in titles of workflow preconditions

---

platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/preview/pdf/StoredFilePdfPreviewPopup.java
platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/preview/pdf/StoredFilePdfRenderer.java

- The DPI value to render PDFs is now configurable.
- Increased to default DPI value from 125 to 250.

PLAT-1256 PDF Rendering: Allow override of default DPI

---

platform-dom/src/main/java/com/softicar/platform/dom/elements/input/auto/DomAutoCompleteDisplayStringDeduplicator.java

measurements with about 11000 business partners
```
before:       75ms 84ms 72ms 69ms 92ms
with this PR: 35ms 30ms 41ms 45ms 37ms
```

PLAT-1255 Optimized DomAutoCompleteDisplayStringDeduplicator

---

README.md
platform-dom/src/main/resources/com/softicar/platform/dom/dom-image-viewer-style.css

https://user-images.githubusercontent.com/90852097/208696291-5c838556-0ae7-4e2b-acc5-2c57b93cfe1e.mp4

PLAT-1257 Add resize to DomImageViewer

---

platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/engine/AbstractTableExportEngine.java

Got rid of some oddly-named and unnecessary private methods.

EXP-2296-4 Table export: Inline some methods

---

platform-emf/src/main/java/com/softicar/platform/emf/data/table/EmfDataTableHeaderRow.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/IEmfDataTableActionHeaderCell.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/column/preselection/TableExportDefaultColumnPreselector.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/export/model/TableExportColumnModelFetcher.java

EXP-2296-8 Table export: Unselect action columns by default

---

platform-dom/src/main/java/com/softicar/platform/dom/elements/input/diagnostics/DomInputDiagnosticsDisplay.java
platform-emf/src/main/java/com/softicar/platform/emf/editor/EmfAttributesDivValidationDiv.java
platform-emf/src/main/java/com/softicar/platform/emf/validation/result/EmfDiagnosticCollection.java
platform-workflow-module/.settings/org.eclipse.jdt.core.prefs
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/AGWorkflow.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/WorkflowPredicates.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/export/WorkflowDtoV1Exporter.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/WorkflowTransitionValidator.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/side/effect/IWorkflowTransitionSideEffect.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersion.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/ActivateWorkflowVersionAction.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/WorkflowVersionIsWellDefinedValidator.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/WorkflowVersionRunnableValidator.java

Test Plan:
- export workflow version
- import workflow version (without change)
- observer import and activation works
- modify exported version to refer to non-existing UUIDs
- import modified workflow version
- observe import works but activation fails with proper error message

PLAT-1239 Workflow Version Runnable Validation

---

platform-emf/src/main/java/com/softicar/platform/emf/form/popup/EmfFormPopup.java
platform-emf/src/main/java/com/softicar/platform/emf/form/popup/EmfFormPopupConfiguration.java
platform-emf/src/main/java/com/softicar/platform/emf/form/popup/IEmfFormPopupConfiguration.java
platform-emf/src/main/java/com/softicar/platform/emf/table/IEmfTable.java
platform-emf/src/main/java/com/softicar/platform/emf/table/configuration/EmfTableConfiguration.java
platform-emf/src/main/java/com/softicar/platform/emf/table/configuration/IEmfTableConfiguration.java

PLAT-1265 IEmfTable: Enable per-table configuration of form popups

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/AGWorkflowTask.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/delegation/AGWorkflowTaskDelegation.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transients/field/WorkflowUserField.java
platform-workflow-module/src/test/java/com/softicar/platform/workflow/module/AbstractWorkflowTest.java
platform-workflow-module/src/test/java/com/softicar/platform/workflow/module/workflow/task/WorkflowUserFieldTest.java

Added function to show delegation in Transient Fields, e.g. in AGInvoice
Testplan:
Tested with an invoice without tasks => Works
Tested with an invoice with delegation => Works
Tested with an invoice with tasks but without delegation => Works

PLAT-1271 WorkflowModule: Correctly show Delegation in WorkflowUser-Transient Field

---

platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/TypeScriptGenerated.js
platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/Popup.ts

PLAT-1277 Fix calmping and scrolling with percent based popup placement

---

platform-dom/src/main/resources/com/softicar/platform/dom/dom-tab-bar-style.css

PLAT-1284 Fix Glitch with Width of Tab Header

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/export/WorkflowDtoV1.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/export/WorkflowDtoV1Exporter.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/export/WorkflowDtoV1Importer.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/WorkflowVersionHashField.java

PLAT-1283 Fix Import and Export of Workflow Versions without Root Node

---

platform-common/src/main/java/com/softicar/platform/common/io/mime/MimeType.java
platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/AGStoredFile.java
platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/StoredFileConverter.java
platform-core-module/src/test/java/com/softicar/platform/core/module/file/stored/AGStoredFileTest.java
platform-core-module/src/test/java/com/softicar/platform/core/module/file/stored/server/AGStoredFileServerTest.java

Unrelated change:
- Fixed an issue in `AGStoredFileServerTest` which caused random test failures due to garbage collection.

PLAT-1290-2 AGStoredFile: Add hasMimeTypeOrExtension, and rework StoredFileConverter

---

platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/preview/pdf/StoredFilePdfRenderer.java

- Previously, `renderPages(AGStoredFile)` caught rendering Exceptions while `renderPages(InputStream, String)` did not.
- Also, added Javadoc to `renderPages(InputStream, String)`.

PLAT-1298 StoredFilePdfRenderer: Fix inconsistent Exception handling

---

platform-common-ocr/src/main/java/com/softicar/platform/common/ocr/tesseract/TesseractOcrTextExtractor.java

Use BMP to exchange data between the PDF renderer and Tesseract, in order to avoid PNG codec overhead.
Saves around 200 to 500ms per page. Performance gains depend on the input file.

PLAT-1302 TesseractOcrTextExtractor: Avoid PNG codec overhead

---

build.gradle
platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/TypeScriptGenerated.js
platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/DelayedExecutor.ts
platform-common/src/main/java/com/softicar/platform/common/code/reference/point/validation/SourceCodeReferencePointValidator.java
platform-common/src/main/java/com/softicar/platform/common/core/java/code/validator/JavaClassValidator.java
platform-common/src/test/java/com/softicar/platform/common/core/java/code/validator/JavaClassValidatorTest.java
platform-core-module/build.gradle
platform-core-module/src/main/java/com/softicar/platform/core/module/CoreCssFiles.java
platform-core-module/src/main/java/com/softicar/platform/core/module/component/external/license/rule/ExternalComponentLicensePredefinedRules.java
platform-core-module/src/main/java/com/softicar/platform/core/module/tinymce/TinyMceInput.java
platform-core-module/src/main/java/com/softicar/platform/core/module/tinymce/TinyMceLibrary.java
platform-core-module/src/main/java/com/softicar/platform/core/module/tinymce/scripts/AbstractTinyMceScript.java
platform-core-module/src/main/java/com/softicar/platform/core/module/tinymce/scripts/TinyMceInitScript.java
platform-core-module/src/main/java/com/softicar/platform/core/module/tinymce/scripts/TinyMceLoadScript.java
platform-core-module/src/main/java/com/softicar/platform/core/module/tinymce/scripts/TinyMceSetModeScript.java
platform-core-module/src/main/resources/com/softicar/platform/core/module/tiny-mce-style.css
platform-dom/src/main/java/com/softicar/platform/dom/document/AbstractDomDocument.java
platform-dom/src/main/java/com/softicar/platform/dom/document/DomDocumentScriptRegistry.java
platform-dom/src/main/java/com/softicar/platform/dom/document/IDomDocument.java
platform-dom/src/main/java/com/softicar/platform/dom/element/IDomElement.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/DomScript.java
platform-dom/src/test/java/com/softicar/platform/dom/document/DomDocumentScriptRegistryTest.java

Because of deadline, the automated tests would be done in a separate PR.
Test Plan:
- create a test page:
```java
public class PlatformTestPageDiv extends DomDiv {
public PlatformTestPageDiv() {
var input = new TinyMceInput();
appendChild(input);
var bar = new DomActionBar();
bar.appendTo(this);
new DomButton()//
.setLabel(IDisplayString.create("Get Value"))
.setClickCallback(() -> new DomModalAlertDialog(IDisplayString.create(input.getValueOrNull())).open())
.appendTo(bar);
new DomButton()//
.setLabel(IDisplayString.create("Set Value"))
.setClickCallback(() -> new DomModalPromptDialog(value -> input.setValue(value), IDisplayString.create("Enter content"), "").open())
.appendTo(bar);
new DomButton()//
.setLabel(IDisplayString.create("Enable"))
.setClickCallback(() -> …
```

EXP-2482 TinyMCE Rich Text Editor Integration

---

platform-core-module/src/main/java/com/softicar/platform/core/module/CoreCssClasses.java
platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
platform-core-module/src/main/java/com/softicar/platform/core/module/daemon/watchdog/state/DaemonWatchdogStatePageDiv.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/AGProgramExecution.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/AGProgramExecutionTable.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/ProgramExecutionRunnableRegistry.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/status/ProgramExecutionStatus.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/status/ProgramExecutionStatusCssPseudoClasses.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/status/ProgramExecutionStatusDisplay.java
platform-core-module/src/main/java/com/softicar/platform/core/module/program/execution/status/ProgramExecutionStatusField.java
platform-core-module/src/main/resources/com/softicar/platform/core/module/program-execution-style.css
platform-emf/src/main/java/com/softicar/platform/emf/attribute/EmfAttributeReorderer.java

PLAT-1318 Program executions: Add a 'Status' column

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/management/WorkflowVersionManagementDiv.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/management/display/element/WorkflowNodeDisplayElement.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/node/AGWorkflowNode.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/node/WorkflowNodeItemCountField.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersion.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersionTable.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/WorkflowVersionItemCountField.java

PLAT-1327 Display of Workflow Item Count

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transients/field/WorkflowUserFieldDiv.java

PLAT-1340 Add Toggle to Show Users in WorkflowUserFieldDiv

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowCssClasses.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/AGWorkflow.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/AGWorkflowTable.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/WorkflowItemCountField.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/WorkflowItemCountInInavticeVersionsColumnHandler.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/WorkflowItemCountInInavticeVersionsField.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/WorkflowManagementPage.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersion.java
platform-workflow-module/src/main/resources/com/softicar/platform/workflow/module/workflow-display-elements-style.css

PLAT-1344 Workflows: Show number of items in inactive versions

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersion.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersionTable.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/WorkflowVersionCurrentVersionField.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/WorkflowVersionIsCurrentField.java

PLAT-1345 Workflow Versions: Add 'current version' column

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowCssClasses.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/version/AGWorkflowVersionTable.java
platform-workflow-module/src/main/resources/com/softicar/platform/workflow/module/workflow-display-elements-style.css

PLAT-1345-2 Showing Current Workflow Version Table Row in Bold

---

platform-ajax/src/main/java/com/softicar/platform/ajax/document/creation/AjaxDocumentCreationService.java
platform-core-module/src/main/java/com/softicar/platform/core/module/page/PageHeaderAndContentDiv.java

EXP-2801 Fix deferred initializers not being processed upon initial document creation

---

platform-ajax/src/main/java/com/softicar/platform/ajax/event/AjaxDomEvent.java
platform-ajax/src/main/java/com/softicar/platform/ajax/request/AjaxRequestMessage.java
platform-ajax/src/main/resources/com/softicar/platform/ajax/engine/TypeScriptGenerated.js
platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/Rect.ts
platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/event/DomEvent.ts
platform-ajax/src/main/typescript/com/softicar/platform/ajax/engine/request/AjaxRequestMessage.ts
platform-ajax/src/test/java/com/softicar/platform/ajax/dom/event/click/AjaxDomClickEventTest.java
platform-ajax/src/test/java/com/softicar/platform/ajax/dom/event/click/AjaxDomDoubleClickEventTest.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/engine/document/DomTestEvent.java
platform-dom/src/main/java/com/softicar/platform/dom/event/IDomEvent.java
platform-emf/src/main/java/com/softicar/platform/emf/management/EmfManagementDataTableRowEventHandler.java

https://user-images.githubusercontent.com/83839745/233589473-07ac7957-4d75-42fe-a467-33f5072dedae.mp4

PLAT-1346 Improved Double-Click vs Text-Selection Behavior

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/IWorkflowTaskQuery.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskDiv.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskQuery.sqml

before:
https://user-images.githubusercontent.com/83839745/236807958-b408048d-b8c0-4e0c-94c3-0a4dc6d18a61.mp4
after:
https://user-images.githubusercontent.com/83839745/236807981-353efa0d-78ec-49ac-a369-7687aefef089.mp4

PLAT-1368 Fixed Refresh Defect in WorkflowTaskDiv

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTasksAndDelegationsUpdater.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/execution/WorkflowTransitionExecutor.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/execution/auto/WorkflowAutoTransitionsExecutor.java
platform-workflow-module/src/test/java/com/softicar/platform/workflow/module/workflow/transition/execution/WorkflowTransitionExecutorTest.java
platform-workflow-module/src/test/java/com/softicar/platform/workflow/module/workflow/transition/execution/auto/WorkflowAutoTransitionExecutionProgramTest.java

- Turned `WorkflowAutoTransitionExecutor` into `WorkflowTransitionExecutor`.
- Extracted `WorkflowTasksAndDelegationsUpdater` from `WorkflowAutoTransitionsExecutor`.

PLAT-1374 Workflow: Improve API to execute pre-defined non-auto transitions

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskDiv.java

https://github.com/softicar/platform/assets/83839745/a8c0c2e6-eff8-4be1-a83b-1cb1cf41dc1c

PLAT-1378 Button to Close Selected Workflow Tasks

---

platform-db-sqml-builtin/src/main/resources/com/softicar/platform/db/sqml/builtin/Aggregate.sqml
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/IWorkflowTaskQuery.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskDiv.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskQuery.sqml

https://github.com/softicar/platform/assets/83839745/8d7353ca-0681-417f-9e45-09f7d6466c76

PLAT-1381 Added Checkbox to Only Show Exclusive Workflow Tasks

---

build.gradle
platform-emf/src/main/java/com/softicar/platform/emf/EmfI18n.java

* PLAT-1382-2 Upgrade mariadbJavaClient to 2.7.9
* Add missing translation

PLAT-1382-2 Upgrade mariadbJavaClient to 2.7.9 (#815)

---

platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/demo/WorkflowDemoObjectStartWorkflowAction.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/IWorkflowTaskQuery.java
platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskQuery.sqml

PLAT-1392 WorkflowTaskPage: Add Workflow

---

platform-common/src/main/java/com/softicar/platform/common/container/data/table/in/memory/AbstractInMemoryDataTable.java
platform-common/src/test/java/com/softicar/platform/common/container/data/table/in/memory/AbstractInMemoryDataTableTest.java

Question: Do we need to add default display elements or something similar somewhere?

PLAT-1394 Support for collections in AbstractInMemoryDataTable

---

platform-demo/src/main/java/com/softicar/platform/demo/person/module/AGDemoPerson.sqml
platform-demo/src/main/java/com/softicar/platform/demo/person/module/AGDemoPersonGenerated.java
platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/value/EmfDataTableValueFilterNode.java

https://github.com/softicar/platform/assets/83839745/c9dac18e-ede2-401a-bd92-40ce1faed0cf

PLAT-1403 Fixed EMF Data Table Value Filter for EMPTY and NOT_EMPTY

---

platform-emf/src/main/java/com/softicar/platform/emf/data/table/filter/list/EmfDataTableFilterListDiv.java

https://github.com/softicar/platform/assets/83839745/115a36f4-5923-4281-94ea-fa0a4891b1be

PLAT-1399 EMF Data Table Filter Input Focus Improvement

---

platform-ajax/src/main/java/com/softicar/platform/ajax/document/service/AbstractAjaxDocumentActionService.java
platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/engine/document/DomDocumentTestExecutionEngine.java
platform-dom/src/main/java/com/softicar/platform/dom/event/DomEventHandlerNodeCaller.java

Before:
https://github.com/softicar/platform/assets/83839745/282cd79f-4469-4169-8840-5fccc19b3554
After:
https://github.com/softicar/platform/assets/83839745/1f2daff3-8079-481e-a1b6-1c16c962e837

PLAT-1410 Fixed Defect Concerning Deferred Initialization and Refresh Bus

---

platform-db/src/main/java/com/softicar/platform/db/runtime/query/filters/DbQueryCollectionFilter.java
platform-db/src/test/java/com/softicar/platform/db/runtime/query/filters/DbQueryCollectionFilterTest.java

before:
https://github.com/softicar/platform/assets/83839745/ee50ba49-b6b3-4f38-ad48-cd04627b68e9
after:
https://github.com/softicar/platform/assets/83839745/dce5ed7d-a924-4be8-a3f1-ab94d10deb87

PLAT-1412 Defect in DbQueryCollectionFilter with Empty Value List

---

platform-demo/src/main/java/com/softicar/platform/demo/invoice/module/invoice/AGDemoInvoiceTable.java
platform-demo/src/test/java/com/softicar/platform/demo/invoice/module/invoice/importing/DemoInvoiceImportTest.java
platform-emf/src/main/java/com/softicar/platform/emf/management/EmfManagementDiv.java
platform-emf/src/main/java/com/softicar/platform/emf/management/importing/EmfImportAction.java

PLAT-1416 Removed Import Button from EmfManagementDiv

---

platform-core-module/src/main/java/com/softicar/platform/core/module/email/mailbox/IMailboxConnection.java
platform-core-module/src/main/java/com/softicar/platform/core/module/email/mailbox/IMailboxConnector.java
platform-core-module/src/main/java/com/softicar/platform/core/module/email/mailbox/imap/ImapConnector.java
platform-core-module/src/main/java/com/softicar/platform/core/module/email/mailbox/imap/Office365ImapConnector.java

Example Code:
```Java
Properties properties = new Properties();
properties.put("mail.imap.partialfetch", false);
try (IMailboxConnection connection = IMailboxConnection.getInstance(emailServer, properties)) {
for (var message: connection.getMessagesInFolder("some-folder")) {
Log.finfo("reading...");
message.writeTo(new ByteArrayOutputStream());
Log.finfo("done");
}
}
```
Without disabling the property `mail.imap.partialfetch`, the download of a 30MB file from Office 365 takes about 30 minutes. With the property disabled, it only takes a few seconds.

PLAT-1420 Support for Additional Properties to IMailboxConnector
